# In my-test-project/.github/workflows/main_ci.yml
name: SAST Scan with Custom Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scan:
    name: Run Vulnerability Scanner
    runs-on: ubuntu-latest
    steps:
      # Step 1: The target repository's code must be checked out first.
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Use your custom action!
      # This tells GitHub to run the action.yml from your other repository.
      - name: Run Custom SAST Scanner
        # Format is {owner}/{repository_name}@{branch_or_tag}
        # Using '@main' means it will always use the latest version from your main branch.
        uses: knanimedali/vulnerability-scanner@main
        # 'with:' is used to pass inputs defined in your action.yml
        # We'll use the default scan_path '.', so 'with' is optional here.
        # with:
        #   scan_path: '.'
